### ISSUE TITLE
Consistencia de rutas frontend - backend

### ISSUE THREAD

**Issue by Tadeo-2404** [Tadeo-2404/FullStack-App-Vivero#29]
La rutas para cliente y para admin deberian tener consistencia
En el caso del cliente se usa / para indicar el LOGIN, donde se pretende mostrar un formulario,
para el frontend en el caso de admin, esta bien poner /inicio para la pagina de incio que muestre todos los productos? o es mejor colocar la ruta / para eso, pensaba colocar / para el LOGIN, y colocar /inicio para el incio

**Comment by ManuelDeAlba** [comment]
Yo pensaba poner "/" como la ruta de inicio, con los productos porque normalmente es la URL de entrada o de inicio
Así los usuarios pueden entrar luego luego a ver los productos sin necesidad de hacer otro paso extra, y ya en dado caso de que quiera iniciar sesión alguien, tendrían que darle a algún boton que lleve a "/login" o algo así para desbloquear esas funciones extras que no son 100% necesarias para todos

Entonces por ahorita tengo pensadas las siguientes rutas (es algo superficial, todavía no pienso bien en todas ni en los mejores nombres)
Rutas de usuario:
/ - Inicio, productos
/inicio-sesion
/registro
/sucursales
...

Rutas exclusivas del administrador (solo se puede acceder si se tiene el rol admin)
/admin/inicio-sesion
/admin/registro
/admin/publicar
/admin/editar/:id
/admin/proveedores
...
