### ISSUE TITLE
Actualizar Esquemas de la base de datos

### ISSUE THREAD

**Issue by Tadeo-2404** [Tadeo-2404/FullStack-App-Vivero#44]
Se debera actualizar todos los esquemas ubicados en la carpeta /db_information para que todas las entidades agregada en backend/models se vean reflejadas. 
Considerar las siguientes entidades:

- Entidad Administrador
- Entidad Compra
- Entidad Producto
- Entidad Proveedor
- Entidad ProveedorProducto
- Entidad Venta
- Entidad VentaProducto

Donde se debera realizar lo siguiente:
- Minimundo
- Diagrama ER que refleje la relacion entre las Entidades
- Esquema conceptual
- Modelo Relacional
- Diccionario de Datos de cada entidad
- Actualizar Tablas en database.sql

**RELACIONES ENTRE ENTIDADES**
**Administrador** -> Compra -> Venta -> Producto
La entidad administrador es la encargada de organizar la app del Vivero, el puede crear productos que se pondran a la venta, puede realizar una venta que contenga una x cantidad de productos, puede realizar una compra de mercancia a un Proveedor que ya este previamente registrado o puede registrar uno nuevo.
- La entidad administrador realiza una compra  a un Proveedor
- La entidad administrador crea un Producto
- La entidad administrador realiza una Venta

**Compra**: Admistrador -> Proveedor
La entidad compra representa la compra de X productos a un Y proveedor, una compra puede contener varios productos que son adquiridos para posteriormente ser mostrados en la tienda
- La entidad compra se realiza del Administrador al Proveedor por una X cantidad de ProveedorProductos
- Un Administrador puede realizar muchas compras, meintras que una compra se realiza a un solo proveedor

**Producto**: Administrador -> Venta
La entidad Producto representa un producto que es ofrecido en el Vivero
- Un producto se agrega por un admistrador donde el admistrador puede agregar muchos productos
- Un producto se asocia a una Venta donde una venta puede contener 1 o mas productos

**Proveedor**:  ProveedorProducto
La entidad Proveedor representa un proveedor que suministra de productos al Vivero, para ello es necesario que el Administrador realice una Compra al Proveedor. Todos los productos que pertenencen al Proveedor se almacenan en una tabla llamada ProveedorProducto, donde cada registro contiene el ID del Proveedor al que pertenece.
- Un proveedor puede ser registrado por el Administrador
- Un pVentaProductovroveedor tiene x cantidad de ProveedorProductos asociados a el, puesto que seran los productos que ese proveedor puede ofrecer para surtir al Vivero

**ProveedorProducto**: Proveedor
La entidad ProveedorProducto representa un producto que pertenece a un Proveedor, donde cada registro es un producto diferente que el Proveedor tiene para ofrecer.  Cada registro contiene el ID del proveedor al que pertenece.
- Un ProveedorProducto pertenece a un Proveedor, donde un Proveedor tiene uno o mas ProveedorProducto

**Venta**: VentaProductos -> Administrador -> Productos
La entidad Venta representa un registro que contiene todos los productos que fueron vendidos, cada venta contiene el total a pagar de los productos que se adquirieron y contiene el ID de la tabla VentaProducto donde se listan los productos que se adquirieron en esa Venta. Una Venta puede ser registrada por el Administrador. Cada Venta puede contener 1 o mas Productos.
- Una venta contiene 1 o mas Productos
- Una venta genera 1 o mas VentaProducto
- Una venta es registrada por el Administrador
- El Administrador puede registrar 1 o mas ventas

**VentaProducto**: Venta
La entidad VentaProdcuto contiene los productos pertenecientes a una Venta donde cada registro contiene el ID del Producto que se vendio, y el ID de la Venta a la que pertenence.
- Una VentaProducto pertenece solo a una Venta
- Una Venta contiene uno o varios VentaProducto
- Una VentaProducto se genera cuando se el Administrador crea una Venta.

**Comment by Tadeo-2404** [comment]
@ManuelDeAlba  para ProveedorProducto, cuando se registre un Proveedor sera prudente crear un formulario para agregar que productos tiene ese Proveedor o que el Proveedor junto a sus ProveedorProducto ya esten generados desde el Backend y el Administrador solo pueda selecionarlos?

**Comment by Tadeo-2404** [comment]
@ManuelDeAlba 
Entonces tendrias que:
-  integrar un Formulario para crear los Productos del Proveedor
-  integrar un Formulario para editar los productos del Proveedor
- Integrar un Formulario para crear proveedores

Que te parece? Las rutas ya estan hechas solo es cuestion de como manejarlo en el FrontEnd, o como tu veas :)

**Comment by ManuelDeAlba** [comment]
@Tadeo-2404 Me parece bien, ahí mientras lo vayamos implementando todo vemos como hacerle :D
