### ISSUE TITLE
Crear Modelo Tabla Compra

### ISSUE THREAD

**Issue by Tadeo-2404** [Tadeo-2404/FullStack-App-Vivero#62]
Compra es los productos que compramos a los proveedores 
- Crear modelo 
- Crear controllers 
- Crear API CREAR EDITAR ELIMINAR MOSTRAR TODOS

**Comment by Tadeo-2404** [comment]
Para continuar con este ISSUE debo estar seguro que usaremos la tabla producto_proveedor para trabajar los controllers y el modelo en base a ello, vease primero #83 @ManuelDeAlba

**Comment by ManuelDeAlba** [comment]
@Tadeo-2404 me parece una buena idea, para poder mostrar los productos que ofrece cada proveedor
