### ISSUE TITLE
Crear Tabla Auxiliar Producto_Proveedor

### ISSUE THREAD

**Issue by Tadeo-2404** [Tadeo-2404/FullStack-App-Vivero#83]
Se requiere una nueva tabla llamada Producto_Proveedor, que lleve el registro de todos los productos que estan disponibles para obtener de un Proveedor, donde:
Un Proveedor es dueño de uno o mas productos, asi, el administrador puede realizar pedidos, seleccionando que productos obtener de un proveedor

Requirimientos:
- Crear Modelo Producto_Proveedor
- Crear Controllers Producto_Proveedor -> POST, GET-ALL, GET-ONE, PUT, DELETE
- Crear archivo de rutas para Producto_Proveedor (similar a Venta_Producto)
- Agregar la tabla al archivo database.sql

**Comment by Tadeo-2404** [comment]
Consideras que es buena idea? yo creo que si es necesario y no seria para nada dificil de implementar puesto que ya tenemos Venta_producto, por lo que muchas caracteristicas se repetirian, que opinas? @ManuelDeAlba

**Comment by ManuelDeAlba** [comment]
@Tadeo-2404 pues podría ser una opción, eso sería para poner un formulario donde registremos lo que cada uno de los proveedores puede ofrecer y después ver esa información como ayuda para saber qué comprar?

**Comment by Tadeo-2404** [comment]
algo por el estilo, aunque faltaria ver como agregar los productos de cada proveedor y relacionarlo pero eso lo vemos despues
