### ISSUE TITLE
Corregir Editar_Venta

### ISSUE THREAD

**Issue by Tadeo-2404** [Tadeo-2404/FullStack-App-Vivero#84]
Para editar una venta seria necesario:
- editar los productos que se relacionan con ella, es decir que pertenencen a venta_producto
- se deberia recibir un arreglo de los productos seleccionados en el formulario Editar-Venta y mandarlo al controller editar_venta
-  se tendria que verificar nuevamente que existen esos productos (tomese crear_venta como ejemplo) 
- se tendrian que actualizar  los productos de venta_productos y si no se encuentran en los productos seleccionados, eliminarlos

**Comment by Tadeo-2404** [comment]
Quieres que lo agregue? @ManuelDeAlba , tiene sentido, porque si se edita una venta se deberian editar los productos relacionados a esa venta

**Comment by ManuelDeAlba** [comment]
@Tadeo-2404 A lo que entendí, me parece bien, entonces sería abrir la venta, agregar o quitar productos en el formulario y volver a hacer el cálculo del precio y la fecha?

**Comment by Tadeo-2404** [comment]
en efecto
